# file: /usr/lib/python3/dist-packages/botocore/exceptions.py
# hypothesis_version: 6.138.2

['Code', 'Error', 'MaxAttemptsReached', 'Message', 'ResponseMetadata', 'RetryAttempts', 'Unknown', '{error_msg}', '{msg}']